---
title: Planning
---

| Séances | Date           | Cours                                             | Préparations | Supports | Devoirs |
| ------- | -------------- | ------------------------------------------------- | ------------ | -------- | ------- |
| 1  | Mardi 21 Janvier    | **1. Introduction aux statistiques descriptives** | 🎥 [Identification d'un échantillon et d'une population](https://fr.khanacademy.org/math/probability/xa88397b6:study-design/samples-surveys/v/identifying-a-sample-and-population) <br> 🎮 [Individus, variables et données qualitatives & quantitatives](https://fr.khanacademy.org/math/cycle-4-v2/xd933de08ca5f2cb4:organisation-et-gestion-de-donnees-statistique/xd933de08ca5f2cb4:representation-d-une-serie-de-donnees/e/individuals-variables-categorical-quantitative-data)| [Séance 1](session-1.qmd) | [Moodle : Test de perfectionnement](https://moodle.essca.fr/mod/quiz/view.php?id=241251) |
| 2  | Vendredi 24 Janvier | **2. Collecte et organisation des données**       | 🎥 []() <br> 🎥 test | [Séance 2](session-2.qmd) | [Moodle : Test de perfectionnement](https://moodle.essca.fr/mod/quiz/view.php?id=241251) |
| 3  | Vendredi 31 Janvier | **3. TP #1**                                         | 🎥 []() <br> 🎥 test | [TP #1](session-3.qmd.qmd) | [Moodle : Test de perfectionnement](https://moodle.essca.fr/mod/quiz/view.php?id=241251) |
| 4  | Vendredi 7 Février  | **4. Représentation graphique des données**       | 🎥 []() <br> 🎥 test | [Séance 3](session-4.qmd) | [Moodle : Test de perfectionnement](https://moodle.essca.fr/mod/quiz/view.php?id=241251) |
| 5  | Vendredi 14 Février | **5. TP #2**                                         | 🎥 []() <br> 🎥 test | [TP #2](session-5.qmd.qmd) | [Moodle : Test de perfectionnement](https://moodle.essca.fr/mod/quiz/view.php?id=241251) |
| 6  | Mardi 18 Février    | **6. Indicateurs de Tendance Centrale**               | 🎥 []() <br> 🎥 test | [Séance 4](session-6.qmd) | [Moodle : Test de perfectionnement](https://moodle.essca.fr/mod/quiz/view.php?id=241251) |
| 7  | Vendredi 21 Février | **7. Mesures de dispersion**                      | 🎥 []() <br> 🎥 test | [Séance 5](session-7.qmd) | [Moodle : Test de perfectionnement](https://moodle.essca.fr/mod/quiz/view.php?id=241251) |
| 8  | Vendredi 7 Mars     | **8. Distribution des données**                   | 🎥 []() <br> 🎥 test | [Séance 6](session-8.qmd) | [Moodle : Test de perfectionnement](https://moodle.essca.fr/mod/quiz/view.php?id=241251) |
| 9  | Vendredi 14 Mars    | **9. TP #3**                                         | 🎥 []() <br> 🎥 test | [TP #3](session-9.qmd) | [Moodle : Test de perfectionnement](https://moodle.essca.fr/mod/quiz/view.php?id=241251) |
| 10 | Vendredi 21 Mars    | **10. Corrélation entre deux variables**           | 🎥 []() <br> 🎥 test | [Séance 7](session-10.qmd) | [Moodle : Test de perfectionnement](https://moodle.essca.fr/mod/quiz/view.php?id=241251) |
| 11 | Vendredi 28 Mars    | **11. TP #4**                                         | 🎥 []() <br> 🎥 test | [TP #4](session-11.qmd) | [Moodle : Test de perfectionnement](https://moodle.essca.fr/mod/quiz/view.php?id=241251) |
| 12 | Vendredi 4 Avril    | **12. TP #5**                                         | 🎥 []() <br> 🎥 test | [TP #5](session-12.qmd) | [Moodle : Test de perfectionnement](https://moodle.essca.fr/mod/quiz/view.php?id=241251) |
