---
title: "6. Indicateurs de Tendance Centrale"
---

::: {.callout-important}
En statistique, un **indicateur de tendance centrale** est une valeur résumant une série statistique pour une `variable quantitative` ou `ordinale`.
:::

Les deux principaux indicateurs de tendance centrale sont la moyenne et la médiane, mais on trouve parfois aussi la valeur centrale (moyenne des valeurs minimale et maximale) ou le mode. Un indicateur de tendance centrale est toujours compris entre les valeurs maximale et minimale. 

##  Moyenne Arithmétique

La moyenne arithmétique, notée $\bar{x}$
$$
\bar{x} = \frac{x_1 + x_2 + \dots + x_n}{n} = \frac{1}{n} \sum_{i=n}^{n} x_i
$$

## Mode

Le `mode` est la valeur la plus fréquente du jeu de données.

::: {.callout-important}
C'est le seul indicateur de tendance centrale qui peut être utilisée sur des données nominales
:::

Une répartition peut être **unimodale** ou **plurimodale** (bimodale, trimodale…), si deux ou plusieurs valeurs de la variable considérée émergent également, voire sans aucun mode (distribution uniforme) si toutes les valeurs de la variable considérée émergent également. Aussi, sa définition ne s’obtient pas directement comme une fonction des termes de la série.

1. **Les variables qualitatives ou dicréte** :

Le mode est la (ou les) modalité(s) da la varaible dont la valeur de l’effectif (ou fréquence) est la plus élevée.

2. **Les variables continues** :

Dans le cas d'une répartition en classes d'amplitudes égales, la classe modale désigne celle qui a le plus fort effectif. La convention est d'appeler mode le centre de la classe modale. Si les classes sont d'amplitudes diverses, il convient de relativiser pour désigner ce paramètre. La classe modale est alors celle qui a la plus forte densité. 


Le mode appartient à la **classe modale** (celle qui possède la plus grande hauteur). Soit $[a; b[$ la classe modale, le mode est calculé ainsi :

$$
Mode = a + \left((b - a) \times \frac{\Delta_1}{\Delta_1 + \Delta_2}\right)
$$

Où:

- $\Delta_1 = h_c - h_c-1$
- $\Delta_2 = h_c - h_c+1$

Avec:

- $h_c$ la hauteur de la classe modale $[a; b[$
- $h_c-1$ la hauteur qui **précède** $[a; b[$
- et $h_c+1$ la hauteur qui **succède** $[a; b[$