---
title: ""
author: "Guillaume Gilles"
format:
  revealjs:
    theme: dark
    chalkboard: true
---

#

##

```{r}
knitr::kable(head(mtcars)[,c("mpg",	"cyl", "disp", "hp", "wt")])
```

Les données ont été extraites du magazine américain *Motor Trend* de 1974 et comprennent la consommation de carburant ainsi que 10 aspects de la conception et des performances automobiles pour 32 voitures (modèles de 1973-74).

- **mpg** : Miles par gallon (US)
- **cyl** : Nombre de cylindres
- **disp** : Cylindrée (pouces cubes)
- **hp** : Puissance brute (chevaux)
- **wt** : Poids (1000 livres)

Ainsi, on peut en déduire que :
1.	 La variable étudiée est qualitative continue
A-	Vraie
B-	Fausse
2.	 L’outil graphique adéquat pour représenter les données de la variable étudiée, est le diagramme en bâtons.
A-	Vraie
B-	Fausse
3.	 Plus de 20% des retraités étudiés ont cotisé moins de 100 trimestres.
A-	Vraie
B-	Fausse
4.	Graphiquement, la modalité la mieux représentée est [80 ; 100 [
A-	Vraie
B-	Fausse
5.	La courbe des fréquences cumulées associée aux données est une courbe en escalier. 
A-	Vraie
B-	Fausse
